trigger:
- main

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      name: default  # This uses your self-hosted agent
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
    - script: |
        dotnet restore HelloFunction/HelloFunction.csproj
        dotnet build HelloFunction/HelloFunction.csproj --configuration $(buildConfiguration)
      displayName: 'Build Function App'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: TestJob
    pool:
      name: default
    steps:
    - script: |
        dotnet test HelloFunction.Tests/HelloFunction.Tests.csproj --configuration $(buildConfiguration)
      displayName: 'Run Unit Tests'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: DeployJob
    pool:
      name: default
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'HelloFunction/bin/Release/net6.0'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        replaceExistingArchive: true

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'ci-cd'
        appType: 'functionApp'
        appName: 'my-azure-function-demo'
        package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
